// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofcyeqavhpkufzkaygbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mY3llcWF2aHBrdWZ6a2F5Z2J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzc4ODYsImV4cCI6MjA2OTY1Mzg4Nn0.Fpg_FLrzb2PRCBENuzOgRMZwUE4piXYTrUpCcDQrUcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});